
-- TOPIC - 1)STORED PROCEDURE, 2) CALLING STORED PROCEDURE.


--- STORED PROCEDURE.

-- 1. A BLOCK OF CODE WHICH IS GETTING STORED IN HANA PERMANANTLY.
-- 2. REUSABLE LIKE F.M IN ABAP.
-- 3. HAS INPUT, OUTPUT AND INOUT PARAMETERS.
-- 4. COMPILE AND STORE (HIGH REUSE).


---------------------------------------------------------------------------
-- CREATING STORED PROCEDURE BY EDITING PREVIOUS ANONYMOUS BLOCK.




CREATE PROCEDURE JANADDNUM(IN X INTEGER, IN Y INTEGER, OUT Z INTEGER)
AS BEGIN 

--COMMENTING BELOW CODE. 
--DECLARE X INTEGER;
--DECLARE Y INTEGER;
--DECLARE Z INTEGER;

X = 20;
Y = 30;

Z := :X + :Y;

-- NO NEED FOR BELOW CODE AS WE ARE RETURNING THE CODE OUT.

-- SELECT :Z FROM DUMMY;


END;
