-- TOPICS- 1)ADDING PARAMETERS TO CURSOR IN SAP SCRIPT.

-----------------------------------------------------
-- THEORY - 
-- CURSOR - CURSORS IN HANA ARE USED TO READ DATA FROM A STORED QUERY(A CURSOR IS ASSIGNED TO A QUERY).
-- TWO WAYS OF CURSOR - 1) PARAMETERIZED, 2) NON-PARAMETERIZED.

------------------------------------------------------
-- REQ - ADDING PARAMETERS TO CURSOR.
------------------------------------------------------

CREATE PROCEDURE SIMPLEPPARAMCURSOR(IN MYCAT VARCHAR(20), OUT PROD1 VARCHAR(40), OUT PROD2 VARCHAR(40))

DEFAULT SCHEMA SAPHANADB
AS BEGIN

-- DECLARE A CURSOR.
DECLARE CURSOR C1(ICAT VARCHAR(20)) FOR SELECT PRODUCT_ID FROM SNWD_PD WHERE CATERGORY = :ICAT;


-- FIRE THE CURSOR.  -- OPEN CURSOR.
OPEN C1(MYCAT);

-- ASK THE CURSOR TO READ DATA FROM MEMORY.
FETCH C1 INTO PROD1;
FETCH C1 INTO PROD2;

END;
----------------------------------------------------
-- CALL SIMPLEPARAMCURSOR(?,?,?)
