-- TYPES OF CONTAINERS - 1)ANONYMOUS BLOCK, 2)STORED PROCEDURE, 3) USER DEFINED FUNCTION(UDF) - A)SCALAR UDF, B)TABLE UDF.

--------------------------------------------------------------------------------------------------------------------------

-- ANONYMOUS BLOCK
-- 1. A BLOCK W/O A NAME IS ANONYMOUS BLOCK.
-- 2. USED ONLY FOR ONE TIME USE 
-- 3. DISPOSABLE.
-- 4. NO REUSE.
-- 5. ONLY FOR TESTING AND TRAINING PURPOSE.
-- 6. EVERY TIME WE RUN THE SYSTEM WILL COMPILE THE CODE.




DO BEGIN 
DECLARE X INTEGER;
DECLARE Y INTEGER;
DECLARE Z INTEGER;

X = 20;
Y = 30;

Z := :X + :Y;

SELECT :Z FROM DUMMY;

END;
