CREATE PROCEDURE GETOIA(
OUT ETAB TABLE( BP_ID VARCHAR(40),
			    COMPANY_NAME VARCHAR(80),
			    OPEN_DAYS BIGINT,
			    GROSS_AMOUNT DECIMAL(15,2),
			    CURRENCY_CODE VARCHAR(4),
			    TAGGING VARCHAR(1)
			    
			   )
)

DEFAULT SCHEMA SAPHANADB
AS BEGIN

-- STEP 1 READ THE CUSTOMIZING,  ALSO READING THE CLIENT VALUE.

SELECT MANDT, MAX_OPEN_DAYS, MAX_AMOUNT, CURRENY_CODE,

