-- TOPICS- 1) LOOP WITH CURSOR USING ARRAY.

-----------------------------------------------------
-- THEORY - 
-- CURSOR - CURSORS IN HANA ARE USED TO READ DATA FROM A STORED QUERY(A CURSOR IS ASSIGNED TO A QUERY).
-- TWO WAYS OF CURSOR - 1) PARAMETERIZED, 2) NON-PARAMETERIZED.

------------------------------------------------------
-- REQ - USING LOOP WITH CURSOR USING ARRAY.
------------------------------------------------------

CREATE PROCEDURE LOOPCURSOR(IN MYCAT VARCHAR(20))

DEFAULT SCHEMA SAPHANADB
AS BEGIN

-- DECLARING THE ARRAY.
DECLARE ALLPROD VARCHAR(40) ARRAY;

-- DECLARE A CURSOR. 
DECLARE CURSOR C1(ICAT VARCHAR(20)) FOR SELECT PRODUCT_ID FROM SNWD_PD WHERE CATEGORY = :ICAT;

-- LOOP TO FETCH DATA DYNAMICALLY
FOR WA AS C1(MYCAT) DO
	ALLPROD[C1::ROWCOUNT] = WA.PRODUCT_ID;
END FOR;

-- NOW READING VALUES FROM ARRAY 
SELECT :ALLPROD FROM DUMMY;

	

